sudo: false
language: python

jobs:
  include:
    - env: TOXENV=flake8
      python: 3.5
    - env: TOXENV=pylint
      python: 3.5
    - env: TOXENV=py35
      python: 3.5
    - env: TOXENV=py36
      python: 3.6
    - env: TOXENV=py37
      python: 3.7
      dist: xenial
      sudo: true
    - env: TOXENV=benchmark
      python: 3.6

install:
  - pip install tox
script:
  - tox
